version: '3'

services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: nginx:latest
    volumes:
      - ./app1:/usr/share/nginx/html:ro

  app2:
    image: nginx:latest
    volumes:
      - ./app2:/usr/share/nginx/html:ro

  app3:
    image: nginx:latest
    volumes:
      - ./app3:/usr/share/nginx/html:ro
